# ============================================================
# Project: War and Democratization in Portugal
# Script: 0_aux_dic_concelhos.R — Overseas Concelho & Name Dictionaries
# Purpose:
#   Define lookup vectors for identifying and tagging casualty records
#   whose birthplace is outside mainland Portugal, including overseas
#   provinces, colonies, and autonomous regions.
#
# Objects defined:
#   - non_cont_concelhos : named character vector
#       • Key: uppercase concelho/freguesia name (OCR-normalized)
#       • Value: territory/country label (e.g., "Angola", "Moçambique")
#   - ultramar_dic_names : named character vector
#       • Key: lowercase place-name variants (ASCII-normalized)
#       • Value: territory/country label
#
# Use in pipeline:
#   - 2_merge.R calls these dictionaries to:
#       • Tag “ultramar” births (non-mainland)
#       • Support fuzzy and manual matching of administrative IDs
#       • Handle historical/variant spellings (e.g., “LOURENCO MARQUES” → Moçambique)
#
# Inputs:    none (hardcoded data structures)
# Outputs:   none (objects in memory)
#
# Notes:
#   - non_cont_concelhos includes historical Portuguese colonial-era names.
#   - ultramar_dic_names includes common OCR variants and diacritic-free forms.
#   - Keys are pre-normalized (upper/lower as indicated) for direct string matching.
#
# Dependencies: none
#
# Author: Gabriel Caseiro (gabrielcaseiro99@gmail.com)
# Date: 2025-08-12
# ============================================================


non_cont_concelhos <- c(
  "BAILUNDO" = "Angola",
  "CHIBIA" = "Angola",
  "NOVA LISBOA" = "Angola",
  "GOLUNGO ALTO" = "Angola",
  "ANDULO" = "Angola",
  "CAOMBO" = "Angola",
  "QUILENGUES" = "Angola",
  "LUBANGO" = "Angola",
  "ALTO CUNENE" = "Angola",
  "CAMACUPA" = "Angola",
  "DEMBOS" = "Angola",
  "VILA LUSO" = "Angola",
  "CAPELONGO" = "Angola",
  "JEOLO DO BENGO" = "Angola",
  "SA DA BANDEIRA" = "Angola",
  "GANDA" = "Angola",
  "ICOLO E BENGO" = "Angola",
  "MOXICO" = "Angola",
  "GANGUELAS" = "Angola",
  "GAMBOS" = "Angola",
  "AMBOIM" = "Angola",
  "QUIBALA" = "Angola",
  "QUISSAMA" = "Angola",
  "ALTO QUANZA" = "Angola",
  "PORTO AMBOIM" = "Angola",
  "MUCARI" = "Angola",
  "LOBITO" = "Angola",
  "DILOLO" = "Angola",
  "SAURIMO" = "Angola",
  "DAMBA" = "Angola",
  "CAMBO" = "Angola",
  "DANDE" = "Angola",
  "CAALA" = "Angola",
  "CAMBAMBE" = "Angola",
  "ALTO ZAMBEZE" = "Angola",
  "BICOIO" = "Angola",
  "LAUNDA" = "Angola",
  "SAMBA" = "Angola",
  "CACHOMBO" = "Angola",
  "NOVO REDONDO" = "Angola",
  "BALOMBO" = "Angola",
  "SILVA PORTO" = "Angola",
  "BELA VISTA" = "Angola",
  "CHINGUAR" = "Angola",
  "MENONGUE" = "Angola",
  "CUBAL" = "Angola",
  "CAZENGO" = "Angola",
  "LONGONJO" = "Angola",
  "NANGAMBA" = "Angola",
  "BONDO E BANGALA" = "Angola",
  "CAZONGO" = "Angola",
  "CELA" = "Angola",
  "NAMBUANGONGO" = "Angola",
  "CACONDA" = "Angola",
  "AMBRIZETE" = "Angola",
  "CATABOLA" = "Angola",
  "SELES" = "Angola",
  "CACUSO" = "Angola",
  "SONGO" = "Angola",
  "CAMABATELA" = "Angola",
  "BOCOIO" = "Angola",
  "LUSO" = "Angola",
  "LIBOLO" = "Angola",
  "GANGUELA" = "Angola",
  "SALAZAR" = "Angola",
  "LUAMBO" = "Angola",
  "FORTE REPUBLICA" = "Angola",
  "DUQUE DE BRAGANCA" = "Angola",
  "CAMANONGUE" = "Angola",
  "CASSAI-SUL" = "Angola",
  "CANGUELAS" = "Angola",
  "CONDA" = "Angola",
  "MUXIMA" = "Angola",
  "MOCAMEDES" = "Angola",
  "CAMBULO" = "Angola",
  "CHITEMBO" = "Angola",
  "CALUQUEMBE" = "Angola",
  "PORTO ALEXANDRE" = "Angola",
  "VILA JOAO BELO" = "Angola",
  "CUNJA" = "Angola",
  "GOA" = "Índia Portuguesa",
  "PORTO AMELIA" = "Moçambique",
  "LOURENCO MARQUES" = "Moçambique",
  "MANHICA" = "Moçambique",
  "MUCHOPES" = "Moçambique",
  "MOCIMBOA DA PRAIA" = "Moçambique",
  "REBAUE" = "Moçambique",
  "NAMPULA" = "Moçambique",
  "RIBAUE" = "Moçambique",
  "QUELIMANE" = "Moçambique",
  "MOSSURIZE" = "Moçambique",
  "BEIRA" = "Moçambique",
  "MECANHELAS" = "Moçambique",
  "MILANGE" = "Moçambique",
  "VILA PAIVA ANDRADA" = "Moçambique",
  "BOLAMA" = "Guiné-Bissau",
  "PICHE" = "Guiné-Bissau",
  "BAFATA" = "Guiné-Bissau",
  "CATIO" = "Guiné-Bissau",
  "FULACUNDA" = "Guiné-Bissau",
  "GABU" = "Guiné-Bissau",
  "CACHEU" = "Guiné-Bissau",
  "MANSOA" = "Guiné-Bissau",
  "FARIM" = "Guiné-Bissau",
  "BISSAU" = "Guiné-Bissau",
  "NOVA LAMEGO" = "Guiné-Bissau",
  "BUBAQUE" = "Guiné-Bissau",
  "GALOMARO" = "Guiné-Bissau",
  "S. DOMINGOS" = "Guiné-Bissau",
  "ALDEIA FORMOSA" = "Guiné-Bissau",
  "TEIXEIRA PINTO" = "Guiné-Bissau",
  "VILACUNDA" = "Guiné-Bissau",
  "CABU" = "Guiné-Bissau",
  "BIJAGOS" = "Guiné-Bissau",
  "MANSABA" = "Guiné-Bissau",
  "CONTUBOEL" = "Guiné-Bissau",
  "BAMBADINCA" = "Guiné-Bissau",
  "BULA" = "Guiné-Bissau",
  "OGO" = "Guiné-Bissau",
  "EMPADA" = "Guiné-Bissau",
  "CACINE" = "Guiné-Bissau",
  "XIME" = "Guiné-Bissau",
  "REGULADO DE SAMA" = "Guiné-Bissau",
  "XITOL" = "Guiné-Bissau",
  "IHAMBATA" = "Guiné-Bissau",
  "ENCHUGAL" = "Guiné-Bissau",
  "TABANCA TUBADIM" = "Guiné-Bissau",
  "SINCHA DJAI CANADU" = "Guiné-Bissau",
  "CANADU CAMAMUDO" = "Guiné-Bissau",
  "CANADU SINCHAMALI" = "Guiné-Bissau",
  "BURUNTUMA" = "Guiné-Bissau",
  "PITA" = "Guiné-Bissau",
  "BOISSORA" = "Guiné-Bissau",
  "ENCHEIA" = "Guiné-Bissau",
  "TITE" = "Guiné-Bissau",
  "COSSE" = "Guiné-Bissau",
  "SONENDU CANJAJU" = "Guiné-Bissau",
  "NAGA" = "Guiné-Bissau",
  "FILIGI" = "Guiné-Bissau",
  "CUNTIMA DE BAIXO" = "Guiné-Bissau",
  "BIGENE" = "Guiné-Bissau",
  "BANDORA" = "Guiné-Bissau",
  "PORTO GOLE" = "Guiné-Bissau",
  "XITOLE" = "Guiné-Bissau",
  "BINAR" = "Guiné-Bissau",
  "CORUBAL" = "Guiné-Bissau",
  "CANDAMA" = "Guiné-Bissau",
  "BINTA" = "Guiné-Bissau",
  "NHACRA" = "Guiné-Bissau",
  "LAVE" = "Guiné-Bissau",
  "XEXE" = "Guiné-Bissau",
  "BERECOBA" = "Guiné-Bissau",
  "BADORA" = "Guiné-Bissau",
  "BAFA" = "Guiné-Bissau",
  "BIOMBO" = "Guiné-Bissau",
  "BALOMBO" = "Angola",
  "BOLOMBO" = "Angola",
  "CAMARA DE LOBOS" = "Portugal (Madeira)",
  "PRAIA DA VITORIA" = "Portugal (Açores)",
  "RIBEIRA BRAVA" = "Portugal (Madeira)",
  "S. ROQUE DO FAIAL" = "Portugal (Madeira)",
  "S. ROQUE DO PICO" = "Portugal (Açores)",
  "S. VICENTE" = "Portugal (Madeira)",
  "SANTA CRUZ" = "Portugal (Madeira)",
  "VILA DO PORTO" = "Portugal (Açores)",
  "VILA FRANCA DO CAMPO" = "Portugal (Açores)",
  "ÍCOLO E BENGO" = "Angola",
  "LOURENCO-MARQUES" = "Moçambique",
  "BADAJOZ" = "Espanha",
  "ICOLO BENGO" = "Angola",
  "S. BENEDITO" = "Angola",
  "VILA NOVA" = "Angola",
  "SANTA COMBA" = "Angola",
  'S. TOME-S. TOME E PRINCIPE'="São Tomé e Príncipe",
  'ILHA DE S. TOME-S. TOME E PRINCIPE'="São Tomé e Príncipe")

ultramar_dic_names<- c(
  'madeira' = "Portugal (Madeira)",
  'angola' = "Angola",
  'mocambique' = "Moçambique",
  'mozambique' = "Moçambique",
  'guine' = "Guiné-Bissau",
  'acoes' = "Portugal (Açores)",
  'acores' = "Portugal (Açores)",
  'cabo verde' = "Cabo Verde",
  'india' = "Índia Portuguesa",
  'macau' = "Macau",
  'huila' = "Angola",
  'benguela' = "Angola",
  'malange' = "Angola",
  'huambo' = "Angola",
  'republica do zaire'= "República Democrática do Congo",
  'bie' = "Angola",
  'marrocos' = "Marrocos",
  'sao tome e principe' = "São Tomé e Príncipe",
  'funchal' = "Portugal (Madeira)",
  'congo ex-belga' = "República Democrática do Congo",
  'luanda' = "Angola",
  'cabinda' = "Angola",
  'ponta delgada' = "Portugal (Açores)",
  'republica do senegal' = "Senegal",
  'republica do brasil' = "Brasil",
  'mocambiue' = "Moçambique",
  'brasil' = "Brasil",
  'inhambane' = "Moçambique",
  'lourenco-marques '= "Moçambique",
  'republica democratica do congo' = "República Democrática do Congo",
  'reino de bissalanca' = "Guiné-Bissau",
  'bissum' = "Guiné-Bissau",
  'bissora' = "Guiné-Bissau"
)
